### ISSUE TITLE
RFE: Add support to SMB v2

### ISSUE THREAD

**Issue by dylan666** [mucommander/mucommander#101]
muCommander uses SBM V1, isn't it?
Please add support to SMB v2 and an option to choose V1 or V2

**Comment by ahadas** [comment]
@dylan666 , right. That's because JCIFS supports only v1 and as far as I understand have no intention to support later versions. Is there a specific feature in v2 that you need? Do you know of any Java library that supports v2?

**Comment by Destynar** [comment]
Due to Wannacry, I disabled SMB1 on my servers completly. And I am looking for a programm to add SMB2 functionality to some stray WinXPs that are still in use. Alas, the only app I coud find that uses its own SMB is this one, and it's still SMB1. And java-based...
I am certainly looking forward to the adding of SMB2+ functionality.

**Comment by MichaelMasuch** [comment]
Would be very thankful if SMB v2 (v3) was supported

**Comment by ahadas** [comment]
@MichaelMasuch Thanks for raising this again. Seems [there are Java clients for v2 and v3 that are worth checking:](https://www.jcifs.org) jcifs-ng and smbj

**Comment by Neustradamus** [comment]
Any news on it?

**Comment by dylan666** [comment]
Any news?

**Comment by ahadas** [comment]
Version 1.1.0 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.1.0-1)

**Comment by Neustradamus** [comment]
@ahadas: Nice, good job, thanks!
