### ISSUE TITLE
[Bug] Quick search erratic behavior

### ISSUE THREAD

**Issue by Andreas0602** [mucommander/mucommander#1017]
### Description

Quick search behaves erratic.

### Steps to reproduce

1. In the left pane, in an empty directory, create the following files: `1 and 1.txt`, `1 and 2.txt`, `1 and 3.txt`, `1 and 4.txt`
2. Make sure that files are sorted by name in ascending alphabetical order
3. Make sure that no files are selected
4. Put the cursor (the blue bar) onto the entry `..`
5. Type `1 and 4`, then press `F5`, then press `Enter`

### Expected behavior

muCommander copies `1 and 4.txt` to the right pane.

### Actual behavior

muCommander copies `1 and 1.txt` and `1 and 2.txt` to the right pane.

### muCommander version

Version: 1.4.0
Build date: 2023/07/16
Build number: 7b14fd0

### Java version

Runtime version: 20
VM name: OpenJDK 64-Bit Server VM
VM version: 20+36
VM vendor: Eclipse Adoptium

### Operating System type and version

Name: Mac OS X
Version: 13.5
Architecture: x86_64

**Comment by ahadas** [comment]
@Andreas0602 that's because `space` is a default keyboard shortcut for the Mark/Unmark action so when you press `1` the quick search starts and the first match is selected; then press `space` and by that mark that selected file and move to the next line; then type `and` + `space` and by that mark the second file that is selected at this point; then press `F5` which copies the two selected files.

when `space` is selected as a shortcut of mark-action, it conflicts with using `space` to specify filenames with a space in their names, but I would prefer to avoid changing the default shortcuts of Mark/Unmark and I think it's handy to mark some of the results of a quick search. I don't see a way to solve this besides changing the keyboard shortcut of Mark/Unmark..

**Comment by pskowronek** [comment]
> The possibility to use quick search for filenames containing spaces is more useful and important in my opinion.

I agree. And it might be very annoying/frustrating - not a very good UX.

**Comment by ahadas** [comment]
I'm ok with prioritizing keys that are valid for quick-search for the string of the quick search over other actions but then we need to make sure every such an action has a keyboard shortcut that is invalid for quick-search - in case of Mark/Unmark the shortcuts are space and insert - and 'insert' doesn't exist in some keyboards...

**Comment by ahadas** [comment]
Version 1.4.0 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.4.0-1)
