### ISSUE TITLE
Release 0.9.3 on GitHub

### ISSUE THREAD

**Issue by dnicodemi** [mucommander/mucommander#1045]
Hello,

Is it possible to publish v0.9.3 on GitHub? As far as I know it is the last version supporting Java 1.8 and, therefore, the 32-bit x86 architecture.

Regards,

Dario

**Comment by hajdam** [comment]
If it's for 32-bit Windows 10+ it should be possible to run current (portable) version of muCommander with for example Temurin JDK:
https://adoptium.net/temurin/releases/?os=windows&arch=x86&version=17

**Comment by hajdam** [comment]
Actually I think it might be also possible to create msi for 32-bit Windows by simply building muCommander with 32-bit JDK without need for any changes to source codes...

**Comment by dnicodemi** [comment]
Hello,

thanks for replying. Actually, the idea was to update this Slackware Linux build script: http://slackbuilds.org/repository/15.0/system/mucommander/.


I don't know if you are familiar with SlackBuilds, basically they are a collection of scripts that allow you to build or re-package applications as Slackware *.tgz packages. The upstream source is not distributed with the script, instead the user has to download it separately.

So, what I was looking for is a link to the 0.9.3 zip archive.

Hope this clarifies,

Dario


Regards,

Dario

**Comment by hajdam** [comment]
Probably some muCommander core dev has older versions somewhere at hand. I found it fortunately present in web archive - if quick file is all you are looking for and not stable link for permanent downloads...
(at least link for Linux download there works for me after redirect)
http://web.archive.org/web/20181117092201/http://www.mucommander.com/

**Comment by hajdam** [comment]
Other option would be to modify build script to use for example zulu openjdk instead
http://slackbuilds.org/repository/15.0/development/zulu-openjdk17/
It has i686 and 32bit arm architecture variant, so you could update muCommander to latest version.

**Comment by dnicodemi** [comment]
Hello,

my only concern is that Oracle dropped official support for the Intel 32 bit platform starting with JDK 11. However, I all considered, I prefer to update the Slackbuild for mucommander-1.3.0 / zulu-openjdk17.

Thanks for your support,

Dario

**Comment by hajdam** [comment]
As additional note, current linux versions are paired with JRE 20, while muCommander is most likely compiled for JRE 11. There might be some rationale behind this, not sure if there is different behavior with different versions. Maybe some core dev could give a hint about this...

**Comment by ahadas** [comment]
> As additional note, current linux versions are paired with JRE 20, while muCommander is most likely compiled for JRE 11. 

that's correct, we bundle Java 20 in the dmg, msi and rpm/deb packages and yet we build the code with compatibility for Java 11

> There might be some rationale behind this, not sure if there is different behavior with different versions. Maybe some core dev could give a hint about this...

the bundled JRE was upgraded several times to address issues (like #536) that have been fixed in recent versions of Java. the code compatibility remained on Java 11 for two reasons: (1) I've noticed some users run muCommander on systems with old versions of Java in the past; and (2) the protocols and formats are designed in a way that they can be reused by other applications and there was an application that did that once, I don't remember which one was it but it was about video editing I think
so as long as we don't have a strong argument for upgrading the code compatibility, I'm ok with keeping it compatible with Java 11

**Comment by ahadas** [comment]
> However, I all considered, I prefer to update the Slackbuild for mucommander-1.3.0 / zulu-openjdk17.

+1
