### ISSUE TITLE
[Enhancement] Select first folder or file when navigating folders

### ISSUE THREAD

**Issue by jlp1701** [mucommander/mucommander#1068]
### Description

When navigating through folders the first row is selected which is the parent directory ("..").

In my opinion it would ease the navigation if the first folder or item (the second row) gets selected when navigating through folders. Of course only when at least one folder exists.

**Comment by ahadas** [comment]
@jlp1701 presenting the parent folder but selecting the next one (when available) seems a bit strange to me, I wonder if it wouldn't be better to make the visibility of the parent folder configurable so that you could just choose to hide the parent folder, what do you think?

**Comment by pskowronek** [comment]
The same here - very strange. When I were to see that I would probably fill a bug :)

However, I'm thinking why pressing 'right' arrow returns back if selection is on `..`? Maybe when navigating with 'right arrow' we could open the first folder automatically, or even go straight into final folder if subsequent folders have only 1 folder and no files (like github shows direct paths if there's nothing else to show - for example being in `mucommander-archiver` folder one could dive directly to `src/main/java/com/mucommander/commons/file/archiver`).

**Comment by ahadas** [comment]
@pskowronek I see your point about the 'right' arrow action, but please note that currently it's an alternative shortcut for 'Open' (its other shortcut is 'enter') so in order to implement what you suggest, which makes sense to me, we would probably want to introduce another action that behaves this way. maybe we can do both things that were we propose above - add such action, and also make the visibility of the parent folder configurable (I think it would be easier for users to notice the latter if we add that configuration to the `View` menu)

**Comment by ahadas** [comment]
Version 1.5.0 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.5.0-1)
