### ISSUE TITLE
[Bug] Unable to access to /Volumes/

### ISSUE THREAD

**Issue by superbonaci** [mucommander/mucommander#1093]
### Is there an existing issue for this?

- [X] I have searched the existing issues (including the closed ones)

### Description

Can't access mounted drives in /Volumes/

### Steps to reproduce

Try to open the folder.

### Expected behavior

Open it.

### Actual behavior

Error:
Folder access error
Failed to read this folder.

### muCommander version

Version: 1.4.0
Build date: 2024/01/12
Build number: cace863

### Java version

Java
Runtime version: 20-internal
VM name: OpenJDK 64-Bit Server VM
VM version: 20-internal-adhoc.ahadas.jdk
VM vendor: Oracle Corporation

### Operating System type and version

OS
Name: Mac OS X
Version: 14.2.1
Architecture: x86_64

### Relevant log output

```shell
no.
```

**Comment by ahadas** [comment]
I can browse /Volumes and the links inside properly so I guess it's a matter to insufficient permissions that were given to muCommander, if you think otherwise and can provide additional information, please reopen
<img width="1212" alt="Screenshot 2024-08-18 at 16 17 07" src="https://github.com/user-attachments/assets/6de7b3c9-a322-4267-ad75-383b3448b112">

**Comment by superbonaci** [comment]
It's working now thanks.
