### ISSUE TITLE
Block select of files marks unexpected set of files

### ISSUE THREAD

**Issue by hellorobusa** [mucommander/mucommander#1103]
### Is there an existing issue for this?

- [X] I have searched the existing issues (including the closed ones)

### Description

If I do a "block select/mark" (click on a file with my mouse and then hold the shift key and click on another file with my mouse), the files that get marked are not the contiguous set of files between the first click and last click inclusive. Instead the resulting set of marked files is somewhat random.

This behavior happens on both Windows and Mac.

![image](https://github.com/mucommander/mucommander/assets/158596406/67d2b64f-6cc0-4c6d-b02f-28f661e59ee0)

### Steps to reproduce

1. Click on a file.
2. Hold the shift key while clicking on another file

### Expected behavior

The files from the file where the first click was made to the file where the shift-click was made should be marked.

### Actual behavior

A set of files that are not within the borders of the list from the first click to the last click are chosen OR only a subset of the files within the borders are chosen.

### Screenshots?

![image](https://github.com/mucommander/mucommander/assets/158596406/f4747b03-96ef-48ef-88ce-ad42496f7199)

### muCommander version

1.3.0

### Java version

Java
Runtime version: 20.0.1
VM name: OpenJDK 64-Bit Server VM
VM version: 20.0.1+9
VM vendor: Eclipse Adoptium

### Operating System type and version

Windows and Mac

**Comment by ShayArtzi** [comment]
Hi,

In the shared example, are you starting with a blank selection? try to hit `ctrl+d` (or `Mark -> Unmark all`) before selecting files.

**Comment by hellorobusa** [comment]
Hi,

Thanks for contacting me. Yes I started with a blank selection by first
pressing ctl-d.

Hopefully you are able to reproduce what I have experienced. I thought for
awhile that if the sort order was by name it was working OK. That's what
seemed to be the case when I discovered this on a Mac. But today on Windows
it did not work even when sorted by name.

--Rob

**Comment by ShayArtzi** [comment]
That is really weird, I cannot reproduce this not on windows and not on a mac. 

Does it happen only in this specific directory? Looks like you get all files that start with the letter `c` selected.

Just to clarify the steps you are making:
1. Click ctrl-d to clear all selections.
2. Click the file named `bfsvc.exe`
3. Shift + click the file named `ChangeLang_Done.tag`
4. All files starting with `c` or `C` are selected as well, irrespective of their order.

Did I get it right?


Could you please try and see if that problem is specific to this set of files? meaning try to do a similar selection on another set of files, in the same directory or another one.

**Comment by hellorobusa** [comment]
Hi, Shay,

I went ahead and created a short video so you can see what I'm doing (
https://youtu.be/o8VuOIxd7is ). A few things about the video:

- There is a watermark across the middle. I just purchased the video
software but have not yet activated it, so my trial version is still
running as a trial.
- The video shows my mouse clicks.
- In the bottom middle of the video you can see what keys I am pressing.

Hopefully this helps you figure things out .

--Rob

**Comment by ShayArtzi** [comment]
Hi Rob,

Thanks for taking the time to capture the video, I watched it and tried one more time to reproduce this locally but unfortunately the selection is working fine on my machine. I did suspect the `+` and `=` characters in your directory names but doesn't look like this is the culprit (I created directories with similar name on my machine, plus your original post is about `c:\windows` which is a plain name without any special characters).

I still want to find the root cause... Could you please let me know what language you have set in `File -> Preferences -> Folders -> Language`? (see attached screenshot)

Thanks!

![image](https://github.com/mucommander/mucommander/assets/7936008/6076161a-1fff-4aab-9a01-584dc9a1e73f)

**Comment by ShayArtzi** [comment]
I think I figured it out! From the screenshot you shared I noticed you are using windows look and feel - and indeed when I switched to it on my machine I was able to reproduce the issue.

As a temporary workaround, you can change your look and feel to `Metal` and see if that helps (see screenshot).

I'll try to debug this later this week and come up with a fix - I'll post further updates here.

![image](https://github.com/mucommander/mucommander/assets/7936008/6f560bd3-1c13-4c62-bc63-8b1e85667938)

**Comment by hellorobusa** [comment]
Ah, good catch. And on my Mac I'm using Mac OS X look and feel.

**Comment by ShayArtzi** [comment]
I was finally able to find the root cause. Apparently Swing's L&F can have an effect on the order of UI-related events.

Specifically, when using Windows L&F, the order of events when selecting multiple files (using the shift key) is:
1. `FileTable::mousePressed`
2. `FileTable::changeSelection`

The code is written under the assumption that the call order is actually reversed, as `changeSelection` is expected to maintain the `lastRow` value (`lastRow` is used in `mousePressed` when calling `setRangeMarked`).

When using non-native L&F that doesn't seem to happen. I have a solution in mind but I'll have to do some more testing. Will post an update once I figure this out.

**Comment by hellorobusa** [comment]
Nice that you figured this out!

**Comment by ShayArtzi** [comment]
PR to address this issue: https://github.com/mucommander/mucommander/pull/1106

**Comment by ahadas** [comment]
Version 1.4.0 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.4.0-1)
