### ISSUE TITLE
[Enhancement] Support encrypting and password-protecting the archive when packing files

### ISSUE THREAD

**Issue by iahung3** [mucommander/mucommander#1129]
### Description

This is a very useful feature. Please add it. Thank you.

**Comment by gerolfscherr** [comment]
Hey, maybe one should revisit this issue. I would love to create password protected zips with muCommander in order to be able to share files with colleagues via usb stick in a secure manner. (preferably AES encrypted).

Would you be interested in password-protected ZIP support? If yes, would you prefer an additional dependency on Zip4j for AES support, or an in-house implementation?
