### ISSUE TITLE
0.9.2 ignores custom Startup folders

### ISSUE THREAD

**Issue by sofortaufsklo** [mucommander/mucommander#120]
Hi guys,

just installed 0.9.2, everything works fine except that it ignores my custom folders, it always remembers the last visited folders, which is pretty annoying.

The configuration is written to preferences.xml:

`    <startup_folder>
        <on_startup>customFolders</on_startup>
        <custom_folders>
            <left>/tmp</left>
            <right>/usr</right>
        </custom_folders>
    </startup_folder>`

it's just being ignored.
I've been using mucommander for years now and that works perfectly fine until 0.9.0.

Is there anything I can do to fix this? Or do I have to wait for 0.9.3?

Thanks alot.

**Comment by ahadas** [comment]
Hi @sofortaufsklo ,yeah, I'm aware of this issue. It is fixed on the master branch (#110). I have no estimation for when 0.9.3 will be released. It might take some time since some symbolic links related stuff may be broken on the master branch. So I'm planning to release a minor version for 0.9.2, I'll backport that fix for this release. Thanks for reporting this!
