### ISSUE TITLE
JRELoaderror

### ISSUE THREAD

**Issue by meinnickwarschonvergeben** [mucommander/mucommander#126]
Hi there,
0.9.2 doesn't load on MacOS with the Errormessage above.
0.9.0 works fine.
What can i do?

**Comment by sky76** [comment]
Me too. 2 Different Macs, each running latest Version of OS X El Capitan.
0.9.0 works
0.9.2 gives JRELoadError

**Comment by Kafkamorph** [comment]
Same here.

**Comment by sky76** [comment]
Probably JRE8.
JRE8 + El Capitan + muCommander 0.9.0 = worked fine.
Recently I've upgraded to macOS Sierra.
JRE8 + Sierra + muCommander 0.9.0 = didn't work, but after switching to muCommander 0.9.2 it works now.

I could check it on my other Mac, where El Capitan is still installed.

How can I detect if there are multiple JRE's installed and which one is the "default" one? The one when you enter "java -version" at the prompt?

**Comment by ITfee** [comment]
I've installed MuCommander 0.9.2 on Mac OS High Sierra 10.13.6 and also had "JRE Load Error" after starting the app. With the JRE mentioned by @Maggsie above it works.

Maybe it is a goog idea to prompt a message instead of the error to lead the user to the Java download page?

**Comment by fkfhain** [comment]
System:
- Oracle Java 10
- Mac OS Mojave

I get "JRELoadError". No error messages in the console ..

**Comment by yotamshtosselfg** [comment]
I get the same error for 0.9.3, Mojave and Java 11 (latest from Oracle).

Project is no longer maintained? :(

**Comment by ahadas** [comment]
@yotamshtosselfg Hi, of course the project is maintained - otherwise you would not have seen new releases ;) muCommander is a Java application and as such requires JRE to run. There is an issue with Java 11 on mac OS - it seems something is missing in the operating system level, and thus JRE is not found. You can create a simple script to run it from the command line or to install an JRE. The right solution from our side though would probably be to bundle JRE into the DMG installation.

**Comment by yotamshtosselfg** [comment]
> @yotamshtosselfg Hi, of course the project is maintained - otherwise you would not have seen new releases ;) muCommander is a Java application and as such requires JRE to run. There is an issue with Java 11 on mac OS - it seems something is missing at the operating system level, and thus JRE is not found. You can create a simple script to run it from the command line or to install an JRE. The right solution from our side though would probably be to bundle JRE into the DMG installation.

Hey - thanks for the quick reply.

I installed the JDK (including jre) via 'brew' and set JAVA_HOME accordingly.

Is there something else I need to set up for muCommanded to find JRE on a (relatively) mint MAC?

10x in advance!

**Comment by yotamshtosselfg** [comment]
"Resolved" after reverting to Oracle Java 10.0.2.

**Comment by Maggsie** [comment]
Cant remember, I am usually up to date with JRE but not sure what the
release was at that time.

**Comment by ahadas** [comment]
@m4xence ack, thanks. I'll publish a new version that is bundled with JRE soon.

**Comment by ahadas** [comment]
Please check out [the latest update of 0.9.3](https://github.com/mucommander/mucommander/releases/tag/0.9.3-3) in which the dmg package includes bundled JRE. Thanks for reporting this!

**Comment by neilyoung** [comment]
My machine (macOS Mojave 10.14.4) offered me a Java 8 update yesterday. I did that and since then I'm receiving "JRELoadError" on attempting to load mucommander. 

java version "1.8.0_191"

And update to 0.9.3 fixed this, but I'm having a new issue with some sftp connection, which require authentication. The error is shown in the screenshot.

![image](https://user-images.githubusercontent.com/731020/57284678-f5fc8480-70b1-11e9-8fce-b2687839b422.png)
