### ISSUE TITLE
AdGuard AdBlocker - Phising detect

### ISSUE THREAD

**Issue by xoango** [mucommander/mucommander#1286]
Hi,

I tried to install in macOS Catalina this app but when I select any of this files suddely apear message from my web navigator (_Mozilla Firefox whith add-on AdGuard AdBlocker_).

2a04b56b4c8d023084abe268b5c69d45 **mucommander-1.5.1-1-noarch.dmg**
a05ae544453acb08e02d2191faf5ea3d **mucommander-1.5.1-1-x86_64.dmg**

**Message**:
"_This page at objects.githubusercontent.com has been reported as a phishing page and has been blocked based on your security preferences._"

Does your program spy on the user's system?

I would appreciate an explanation on this, thank you very much for your time.

xoango.

**Comment by ShayArtzi** [comment]
Hi @xoango,

You can be rest assured - muCommander is an open source project maintained by volunteers. The full source code is available right here in our Github repository and anyone can examine it for potential issues. If you have any concerns about installing it on your machine, my advise would be to just upload the binary file to [virus total](https://www.virustotal.com) which will run the binary file through multiple anti-virus engines and will provide you with a report so you can decide for yourself.

The messages you are seeing in your browser is probably a false positive. Since anyone can host content on Github, it probably has the potential to host malicious files as well. This is of course not the case for muCommander (but again, check for yourself - it's always a good idea!).

Best,
Shay

**Comment by ahadas** [comment]
yeah, I can see why tools classify `objects.githubusercontent.com` as a suspicious place but artifacts of muCommander published there are safe
