### ISSUE TITLE
Files properties in Windows?

### ISSUE THREAD

**Issue by SGvagon** [mucommander/mucommander#172]
Hello,

I don't know is it a bug or feature, but when I right clicking on any file and choose Properties, it not show Windows properties, but only MuCommander window with some info about files, but I would like to show Windows properties window.
https://ctrlv.cz/shots/2018/11/14/2yJI.png

**Comment by ahadas** [comment]
Hi @SGvagon ,
Well, we aim at making muCommander cross-platform as much as possible.
That means, that unless there is some significant benefit in providing OS-specific part (e.g., moving files to trash), we would like our features to be cross-OS - so that's the reason for providing a file-properties dialog that is common to all operating systems rather than using that of, e.g., Windows.

So the question is why would you prefer the one provided by Windows.
Had we find a feature or a set of features that are missing by our dialog, I would say that we need to consider if we can add them to our dialog as opposed to invoking the dialog provided by Windows.

On another subject, IIRC you reported that moving files to trash work didn't work with version 0.9.2, right? does it work alright for you with 0.9.3?

**Comment by SGvagon** [comment]
Yes, in 0.9.2 moving to trash not work on W7 x64bit (stop on 100%) , but with 0.9.3 is everything allright and I can moving files to trash :) . Thank you for quick reply and quick 0.9.3 released.

And I prefer Windows properties, because there is lots of features which Windows have, including info about meta tags (for ex. resolution, mpx, ... on photos) or compatibility tab, quick move to the install folder on shortcuts, edit start parameters, etc. .

**Comment by ahadas** [comment]
@SGvagon I see. In that case, I would say that it makes sense to enable opening the native dialog.
I think we should keep our own dialog as the default one though and allow switching to the native dialog on platforms that it is supported for. Does it make sense?

**Comment by SGvagon** [comment]
Yes, it would be great :) .

**Comment by sskras** [comment]
I second that request. 

PS. The option for this switch should probably be integrated / organized into some bigger hierarchical tree like one used for Total Commander, eg.:
![](http://beerpla.net/wp-content/uploads/HowToShowHiddenInvisibleFilesInTotalComm_14844/image.png)
(to avoid cluttering the current tabs such as Appearance)

But that probably should be asked in a separate issue (RFC). Which I could do later.

**Comment by pskowronek** [comment]
If it is still an issue please re-open.
