### ISSUE TITLE
OS X High Sierra: Cannot overwrite existing file

### ISSUE THREAD

**Issue by rhstanton** [mucommander/mucommander#177]
When trying to copy files using 0.9.3, if there's an existing file and I ask to overwrite it, muCommander acts as if it's about to do so, but progress never gets beyond zero.

**Comment by ahadas** [comment]
Thank you for reporting this! A minor version with the fix would be released soon.

**Comment by neilyoung** [comment]
Having the same issue with Mojave. The copy dialog pretends to overwrite, but nothing happens

**Comment by neilyoung** [comment]
@ahadas Your fix is working

**Comment by neilyoung** [comment]
@ahadas When do you plan to release that publicly? My build is now complaining that there is a newer version on the Internet, since the version of my build is ?

**Comment by ahadas** [comment]
@neilyoung Thanks for confirming that the fix works. I actually planned to release it already but the few issues were opened (e.g., #178) and I wanted to see whether those are real issues and whether it makes sense to stall 0.9.3.1 a bit to include more fixes. At the moment, I don't see any other real issue so I plan to release it in the next few days.

**Comment by neilyoung** [comment]
@ahadas Thanks for the follow up. Everything is fine. After having rolled my own DMG and installed from your patch the version number was OK and I got no "new app" notifications anymore. Can wait until your next official release. Keep up doing this :) As a fan of Norton Commander since decades I like your tool on macOS
