### ISSUE TITLE
A few issues with "Show/Hide Columns" menu item.

### ISSUE THREAD

**Issue by tikomir** [mucommander/mucommander#211]
1. Menu item "View -> Show/Hide Columns -> Extensions" behaves unexceptionally. On a Windows platform it doesn't show/hide file extensions but icons.
2. Checking/unchecking items in this menu applies only to the current view and not to the other view.

**Comment by ahadas** [comment]
@tikomir Yes, the "EXTENSIONS" column presents icons but note that those icons are set according the the file extensions. Could you propose better naming? I would prefer to keep it this way unless we find an alternative name that is significantly better.

Regarding the second part, I see your point - you would expect this setting to be applied on both panels, right? I can think of a use-case in which someone would want to hide a column that is irrelevant for a file protocol (e.g., virtual disks in oVirt) and keep in the other panel, where is it relevant (e.g., local files). So maybe we should think of a way to enable the user to choose whether to apply this on the active panel or on both panels.

**Comment by tikomir** [comment]
The term "EXTENSIONS" is not appropriate as it doesn't do anything with extensions but only with icons. Use the term "ICONS" instead. Perhaps you are not aware, but there is a setting (i.e. preference) and a menu item in Windows Explorer that can be used to hide extension for "known" file types, i.e. registered file types. E.g. on a new installation of Win10 on my computer, this setting hides file extensions like "txt", "html", "exe" etc, but doesn't hide "java" as I did not registered any application to handle Java files explicitly. Perhaps, such setting and menu item could be added to MC in the future.
https://www.itprotoday.com/windows-78/registered-file-types
https://it.nmu.edu/docs/common-windows-file-extensions
https://www.computerhope.com/issues/ch001789.htm

Regarding the applying the aforementioned setting "View -> Show/Hide Columns -> Extensions" to both panels, you could add a menu item "View -> Show/Hide Columns -> Apply to both panels" before "Extensions" menu item. Of course, add a separator bar between them.

**Comment by kousalik** [comment]
As a newcomer I've got to say @tikomir has a point. ICONS make much better sense.

**Comment by ahadas** [comment]
There are three things reported in this issue:
1. Changing the title of the 'Extension' column to 'Icons'
2. Hide file extensions of "known" file types
3. Enable showing/hiding a column in both panels with a single click

After a long time that we didn't get any contribution, it's time to close it
I personally don't think that 'Icons' would be a better title (but that's subjective of course), I don't think we should have such a tight integration with the operating system to get the file extensions it "knows", and don't think it is worth the time to add the third part since it's not something one is likely to do often
That said, if you care about any of this and willing to implement the change, let's discuss it further
