### ISSUE TITLE
Newcomer's confusion

### ISSUE THREAD

**Issue by kachkaev** [mucommander/mucommander#27]
Hi guys,

I've been using muCommander for a few years after switching from Windows to OSX. Really glad to see that the project is still live and that the repo has been moved to github. This is just awesome!

MuCommander has been a perfect replacement for TotalCommander and it still is! The reason why I started searching for it again is because I recently needed something similar on Ubuntu 16.04.

As a person who has not been following the changes in the project for a while, I'm a bit confused with what's being maintained and what's abandoned. Here's what I've discovered:
- **Official website http://www.mucommander.com**
  - Says (c) 2002-2016 in the footer
  - Has links to trac, but they don't work
  - Has links to nightly builds; they work but it is unclear when was the last night and what code base has been used for building
- **GitHub-powered website http://mucommander.github.io**
  - Says (c) 2002-2015 in the footer
  - Has links to guthub issues
  - Has no links to nightly builds
  - Has a link to twitter: https://twitter.com/muCommander
- **Twitter account https://twitter.com/muCommander**
  - Suggests to check out github, but has no link to any website
  - Has only one tweet
- **This repo**
  - Some commits are new, which is very promising
  - Recent changelog reports that a bug I'm currently facing in 0.9.0 on Ubuntu is fixed (re installation via software center)
  - Empty wiki pages
  - "Official website: http://www.mucommander.com Copyright (C) 2002-2014 Maxence Bernard."
  - A few links to http://mucommander.atlassian.net, which do not work
  - It is unclear where to get the nightly builds and whether they exist at all

Given the above contradictions, it is difficult and time-consuming to figure out the actual state of the project. Here's what could make the newcomers' life easier in my opinion:
- [x]  2015 -> 2016 on the github-powered website
- [x] a warning message on http://www.mucommander.com or even a permanent HTTP redirect to a new website (if possible)
- [x] A link to http://mucommander.github.io instead of http://www.mucommander.com in README.md
- [x] A link to http://mucommander.github.io from the twitter account + a couple of new tweets maybe
- [x] A comment on the availability of the nightly builds on http://mucommander.github.io. Not sure if it is easy to generate and keep them on github pages at all, so if not and there's no 3rd-party CI that can generate them, it would be nice if the users would know about. When I saw that my bug has been fixed, I remembered seeing links to nightly builds years ago and went searching for them. Downloading a build from the old website gave no affect. Someone else is likely to follow the same route as me.
- [x] Some clarifications on the wiki pages might help. Or maybe those pages can be deleted completely together with the links to them on http://mucommander.github.io. Markdown files in the repo do the same great job in most of the cases and they are much easier to collaborate on.

Hope that my feedback helps you guys! The efforts you're taking to bring the project back to life are very helpful to many!

**Comment by ahadas** [comment]
Hi @kachkaev ,
Thanks for the detail explanation!
You're mostly right.
The website on github was published as a proof-of-concept (and therefore the single tweet and saying 2015 instead of 2016) before redirecting mucommander.com to it. This is an unfinished task.
And we used to generate nightly builds using jenkins but we lost this ability when stopped working with jenkins and having the website hosted locally. I can build it some 'nightly build' from the master branch for you if you like - for which OS?
We should definitely update the documentation - not sure if markdown files in the repository is better than using the wiki pages on github. That's something to think about.
But first I want to be able to release a version based on current master.

Regards,
Arik

**Comment by kachkaev** [comment]
Thank you for the reply Arik,

I was looking for an Ubuntu build to be able to check if one of your recent bugfixes makes the app workable. It will be great if you do one.

Looks like you've done quite a lot of work, which probably deserves a version, not just a build. How about releasing 9.0.2 at some point in the near future? It does not need to be perfect, since it's always possible to issue 9.0.3 etc. :–)

Thanks again for your efforts!

**Comment by ahadas** [comment]
Hi,
I've created a snapshot version for Ubuntu.
In order to install it you can either do:
1. echo "deb https://dl.bintray.com/mucommander/mucommander-deb jessie utilities" | sudo tee -a /etc/apt/sources.list
and then: sudo apt-get install mucommander
or 
2. download it from:
https://bintray.com/mucommander/mucommander-deb/download_file?file_path=pool%2Futilities%2Fm%2Fmucommander-deb%2Fmucommander_0.9.1_all.deb
and then: sudo apt-get install ./mucommander_0.9.1_all.deb

Please note that this version is based on the master branch and due to recent packaging related changes some things might not work properly. Any feedback would be much appreciated!

**Comment by kachkaev** [comment]
Thank you Arik! I'll look at this on Tuesday – just don't have that Ubuntu box with me right now.

**Comment by kachkaev** [comment]
Great, it works! For those who find that muCommander does not launch after steps by @ahadas, install JRE and open the app again:
https://www.digitalocean.com/community/tutorials/how-to-install-java-on-ubuntu-with-apt-get

**Comment by ahadas** [comment]
Thanks for the confirmation!
I'm not closing it yet as I need to remember to document it

**Comment by kachkaev** [comment]
Things are so much clearer now  thanks for your work! I updated some of the checkboxes. Feel free to close this issues once you think that the remaining issues are more or less addressed.

**Comment by ahadas** [comment]
Just added a link to the nightly build on the website and I believe the other things have already been addressed
