### ISSUE TITLE
Updating to Java 8?

### ISSUE THREAD

**Issue by aadrian** [mucommander/mucommander#28]
Hi,

Any plans updating to Java 8?

Most users (except a few in big companies) can't even download an actual 1.6 or 1. 7 nowadays.
For OSX users, the outdated Apple 1.6 should not be used (but there's always an actual Java 8 ```brew cask```)

Thank you.

**Comment by ahadas** [comment]
Hi @aadrian,

Well, traditionally we were trying to be compatible with the Java version that is built-in in latest version of Mac OS X. If we upgrade the Java version, we would need to provide muCommander bundled with JRE - another change that I prefer to avoid for the upcoming release.

That being said, if it turns out to be non trivial to keep that compatibility with Java 1.6 in the master branch then we might break it and provide muCommander bundled with JRE. Anyway, after the next release we will upgrade the Java version.

Regards,
Arik

**Comment by VladRassokhin** [comment]
Unfortunately, even well-compressed Oracle/OpenJDK jre is about 70 megabytes == ~15 times of muCommander.

Note that Java is no longer pre-installed on OS X, AFAIK. So user have to install jre anyway.

**Comment by VladRassokhin** [comment]
Maybe it would be good decision to use homebrew on OS X to deliver muCommander, as casc may add dependecy on latest jre 8.

BTW. For now IDEA reports some usages of 1.7/1.8 in code related to ui (generics in swing types).

**Comment by ahadas** [comment]
@VladRassokhin , exactly - adding another 70mb kind of breaks the "lightweight" in "muCommander is a lightweight, cross-platform file manager..."
Using homebrew - yeah, that's something to consider.
And yep, it was reported that the master branch depends on things that are not compatible with Java 1.6 - that's the next thing I plan to look at.
