### ISSUE TITLE
Enhancing drag&drop

### ISSUE THREAD

**Issue by sebastian-lempert** [mucommander/mucommander#32]
## 1) Enable drag&drop in the same window

Using a dual pane file manager means that very often the two panes do not show the contents of the same folder / path. While most of the file operations happen between two panes sometimes it would be nevertheless very useful to be able to drag&drop a file on a folder that is visible in the same window only.

**Thus is it possible to enable drag&drop in the same window?**
## 2) Always indicate the target path and the file operation during drag&drop

While dragging a file without pressing any key a small "+" icon is displayed to indicate that a copy operation will be performed if the file is dropped at the mouse pointers position. Furthermore it is possible to choose the move operation instead of the default copy operation while pressing the corresponding key (on OS X: Cmd) during dragging. But unfortunately there is no icon to indicate the move operation.

**Thus is it possible to indicate the move operation with a proper icon (e.g. "-")?**
## 3) Always highlight the target folder row

Often a file should be dropped on a certain folder that is embedded in a sequence of folders. Furthermore as a rule the length of the name of a folder is shorter than the length of the corresponding row in the pane. Since the targeted folder / the row of the target folder is not highlighted in the end one might target the wrong folder and might end up with an unwanted file operation.

**Thus is it possible to highlight the row of the folder while a file is dragged onto it and before this file is dropped onto it?**

Thank you very much for all your efforts & best regards!

**Comment by Meilenstein** [comment]
It would be great to see idea nr. 1) in the next version :-)

**Comment by ahadas** [comment]
nice ideas! sound like something we can consider for the next release (at least some of them)
@sebastian-lempert, sorry for the late response - I missed this somehow..

please try 0.9.1rc. since it has been a while since the last release and many things have changed, I would like to get some feedback before releasing 0.9.1 as a stable release:
[1] https://github.com/mucommander/mucommander/releases/tag/0.9.1rc

**Comment by sandreas** [comment]
I forked mucommander to implement the Drag & Drop in the same FileTable, because its something i would love to have...

Unfortunately i don't know exactly where to start... I guess that it has to be implemented in the `FileTable` class, since it implements the `MouseListener` and `MouseMotionListener`, but since it is a `JTable` and there are already some `MouseEvents` handled, I'm not sure, if the following would work?

```
// add to constructor
this.setDragEnabled(true);
this.setDropMode(DropMode.INSERT_ROWS);
table.setTransferHandler(new TableRowTransferHandler(table)); 

// implement reorderable interface
public interface Reorderable {
   public void reorder(int fromIndex, int toIndex);
}

/**
 * Handles drag & drop row reordering
 */
public class TableRowTransferHandler extends TransferHandler {
   private final DataFlavor localObjectFlavor = new ActivationDataFlavor(Integer.class, "application/x-java-Integer;class=java.lang.Integer", "Integer Row Index");
   private JTable           table             = null;

   public TableRowTransferHandler(JTable table) {
      this.table = table;
   }

   @Override
   protected Transferable createTransferable(JComponent c) {
      assert (c == table);
      return new DataHandler(new Integer(table.getSelectedRow()), localObjectFlavor.getMimeType());
   }

   @Override
   public boolean canImport(TransferHandler.TransferSupport info) {
      boolean b = info.getComponent() == table && info.isDrop() && info.isDataFlavorSupported(localObjectFlavor);
      table.setCursor(b ? DragSource.DefaultMoveDrop : DragSource.DefaultMoveNoDrop);
      return b;
   }

   @Override
   public int getSourceActions(JComponent c) {
      return TransferHandler.COPY_OR_MOVE;
   }

   @Override
   public boolean importData(TransferHandler.TransferSupport info) {
      JTable target = (JTable) info.getComponent();
      JTable.DropLocation dl = (JTable.DropLocation) info.getDropLocation();
      int index = dl.getRow();
      // ....

return true;
   }

   @Override
   protected void exportDone(JComponent c, Transferable t, int act) {
      if ((act == TransferHandler.MOVE) || (act == TransferHandler.NONE)) {
         table.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
      }
   }

}
```

And since there are some workarounds (e.g. the Thread.sleep(800)), the current behaviour is, that clicking and dragging an item results in another item beeing marked, that the one that has been clicked. 

Perhaps someone could point me into the right direction?

**Comment by ahadas** [comment]
Hi @sandreas , thank you for looking into that! I would suggest starting at the `com.mucommander.ui.dnd` package. 

The first part seems to result from [this part in FileDropTargetListener](https://github.com/mucommander/mucommander/blob/master/mucommander-core/src/main/java/com/mucommander/ui/dnd/FileDropTargetListener.java#L171).

As for the second part, I'm not sure where this icon comes from - didn't see it in our repository, it may be the default one provided by Java. I'm not sure the '-' option is the best one since we use it for deletion. We may want to use the icons of copy-file and move-file in that context as well, if possible.

I assume the third part would require changes to the FileTable, detecting "mouse over" while during drag & drop operation is going on.

**Comment by sandreas** [comment]
Thank you... :-) atm i'm trying to get my IDE working (IntelliJ Ultimate) but debugging fails for some reason with the gradle task `runOsgi`. I'll tell you when I'm ready.

**Comment by ahadas** [comment]
I'm using Eclipse but the debugging process should be similar - please look at the `How to Debug` section [here](https://github.com/mucommander/mucommander)

**Comment by sandreas** [comment]
Thank you very much for supporting, debugging works. Added some adjustments to the `build.gradle` to make it easier. I'll try to send a pull request for documentation and gradle improvements in the next days - just a few lines.

Next I'll try to enhance the drag and drop thingy...

**Comment by UristMcGeorge** [comment]
hi, not sure if voting for issues is a thing here, if it is i'd like to vote to enable drag&drop in the same window please :)

**Comment by sandreas** [comment]
I did not finish my changes... did not have the time. If someone is willing to implement this you should not wait on my PR any more :-)

**Comment by pskowronek** [comment]
If it is still an issue please re-open.
