### ISSUE TITLE
JRELoadError with muCommander 0.9.1rc

### ISSUE THREAD

**Issue by ITfee** [mucommander/mucommander#34]
I've updated from version 0.9.0 to 0.9.1rc today. After I've deactivated Gatekeeper in order to launch muCommander I get an error message saying

> JRELoadError

I think because of the old java I needed to install on Mac OS X 10.11.6 (El Capitan) to make muCommander 0.9.0 run or is this some kind of bug?

**Comment by ahadas** [comment]
Hi @ITfee ,
Thanks for the input.
I believe that upgrading to newer version of Java will solve it,
but as 0.9.1rc is supposed to run with the old version too, I'll try to reproduce it on my machine

**Comment by ahadas** [comment]
@ITfee , I managed to reproduce it.
The problem is that the published dmg was not compiled with Apple's jdk.
I will create another dmg file that works with the old Apple's Java.
Unfortunately, it would probably be twice as big (~20MB) because the current gradle plugins I'm using do not work with Java 1.6.

**Comment by ahadas** [comment]
@ITfee , could you please try the new dmg I've created for Apple's java:
https://github.com/mucommander/mucommander/releases/download/0.9.1rc/mucommander-0.9.1rc-apple-java.dmg

**Comment by ahadas** [comment]
Verified using Apple's java that produced JRELoadError with previous dmg file that it works properly with the dmg file mentioned above.
Feel free to reopen if it still reproduces for you with this dmg file.

**Comment by DavMorr** [comment]
This is still an issue with v 0.9.2 (mucommander-0.9.2.dmg) .

**Comment by sky76** [comment]
I resolved this issue by installing the latest JRE from Oracle.
But this was a nearly vanilla install of El Capitan. Maybe if you have upgraded from Mavericks to El Capitan or similar, issues may occur due to multiple JREs installed.
Going to test this with my MBP, where once there was Mavericks installed.
