### ISSUE TITLE
Allow both gnome-open and xdg-open/gvfs-open for Gnome desktops

### ISSUE THREAD

**Issue by sdruskat** [mucommander/mucommander#37]
The default `gnome-open` command for Gnome desktops seems to have changed to `gvfs-open`.

Therefore it'd be good to not only check for the availability of `gnome-open`, but also if `gvfs-open` and perhaps also its platform-independent pendant `xdg-open`.

**Comment by ahadas** [comment]
@sdruskat , thank you for pointing this out!
I changed it - in order to 'guess' whether the desktop is of type GNOME we now look for gvfs-open as well. There is no point in checking xdg-open for this because, as you mentioned, it is desktop agnostic. But xdg-open is now used as the 'file opener' in order to leverage the fact it works with both older and newer GNOME versions.
These changes are also backported to 0.9.1 branch.

**Comment by sdruskat** [comment]
@ahadas, cool, thanks. It'd be really great to have this backported to 0.9.1, as without it, you cannot natively open *any* files on Ubuntu 16.04... Just discovered this issue but won't report as bug as it is already fixed :). `master` build works as expected. What's the schedule for 0.9.1rc?

I'll try and contribute in the future if I get some time.

**Comment by ahadas** [comment]
Thanks for the verification!
As for the schedule of 0.9.1 - I think it is currently in a relatively good shape. I hope to be able to release another release candidate version on the weekend, and if no major issue is found and once I finish with implementing the packaging capabilities we used to have, the stable version of 0.9.1 can be published soon afterwards.

As for future contributions - they are always welcome :) we need to fill a significant gap of couple of years of inactivity. Some forks added nice functionality but they left much to be desired and proprietary tools made major progress. But with good communities of developers and users we can fill that gap.

**Comment by ahadas** [comment]
@sdruskat , note that rc2 is not available at:
https://github.com/mucommander/mucommander/releases/tag/0.9.1rc2
