### ISSUE TITLE
full Java 11+ support

### ISSUE THREAD

**Issue by sfuerte** [mucommander/mucommander#394]
The current builds use embedded JRE 8 into the packages. 

Changing JRE via `change_jre.command` or building from source and trying to launch leads to `JRELoadError`. 

At the same time, `gradle runOsgi` or `java -jar build/macApp/muCommander.app/Contents/Java/mucommander-0.9.6.jar` work completely fine:

```
23:39:26.874 [FelixStartLevel] INFO com.mucommander.commons.runtime.OsFamily - Current OS family: Mac OS X
23:39:26.879 [FelixStartLevel] INFO com.mucommander.commons.runtime.JavaVersion - Current Java version: 11
23:39:26.879 [FelixStartLevel] INFO com.mucommander.commons.runtime.JavaVersion - Current JVM architecture: aarch64
...
23:39:27.605 [FelixStartLevel] INFO com.mucommander.desktop.macos.CoreServiceTracker - CoreService is registered: com.mucommander.Activator$1@47a98546
```

OS & Java versions:
```
> sw_vers
ProductName:	macOS
ProductVersion:	11.1

> java --version
openjdk 11.0.9.1 2020-11-04 LTS
OpenJDK Runtime Environment Zulu11.43+1015-CA (build 11.0.9.1+1-LTS)
OpenJDK 64-Bit Server VM Zulu11.43+1015-CA (build 11.0.9.1+1-LTS, mixed mode)
```

**Comment by sfuerte** [comment]
I guess, partially it's due to https://github.com/crotwell/gradle-macappbundle/issues/56

**Comment by ahadas** [comment]
Hi @sfuerte ,

Thanks for filing this issue. Your observation is right - 
Java 9+ is supported when building the project from source but Java 8 is intended for the upcoming official release(s).

The reason for not packaging Java 11+ into the official release is not due to the packaging process. As a matter of fact, Java 11 was previously packaged into a stable release of muCommander. But as it turned out, recent Java versions for macOS don't work as good as Java 8 which is still being maintained by AdoptOpenJDK.

However, I didn't want to limit developers to use Java 8 so it is possible to use Java 9+ when building the project from source.

This situation is not ideal, I agree. It complicates the release process and developers don't use the same code end-users would eventually use (although the vast majority is the same). But that's the best solution I found until we are able to provide reliable stable releases bundled with Java 11+.

As for the `change_jre.command` script, it as not intended for upgrading to a new version of the JDK but to an older ones that work on older versions of macOS/mac os x. But it can be a nice addition to use this script to upgrade to a newer version of Java.

**Comment by sfuerte** [comment]
Hi @ahadas,

Any possibility or potential considerations of dropping the JRE8 from official releases and rely on system Java version? Potentially via two packages: system Java dependent and embedded JRE? 

As for Java 11+,
while the project does run under it via `java -jar` directly (and potentially on other platforms), though a can of worms on macOS is that `edu.sc.seis.macAppBundle` (https://github.com/crotwell/gradle-macappbundle) or its fork `com.github.cr0.macappbundle` (https://github.com/cr0/gradle-macappbundle-plugin) are rather outdated, with the former posted directly in its `README`:

> Note I am no longer able to actively develop this project.
> I will consider pull requests, but I believe that the Java world has changed significantly over the past several years, and this plugin may no longer be the recommended way to package a Java app for OSX.

There is a fork with some fixes to the latter project the might help with the problem though - https://github.com/w8wjb/gradle-macappbundle-plugin/tree/openjdk

**Comment by sfuerte** [comment]
@ahadas, on the second thought (and after multiple troubleshooting), it might be not that bad. While `edu.sc.seis.macAppBundle`'s both Apple and Oracle app launchers are broken on Java 11 but `universalJavaApplicationStub` works fine. 

Here is a proof of concept - https://github.com/sfuerte/mucommander/commit/0435aa206894bf69045b1a0056bc0f8c6191f994

The resulted bundle is less than a quarter of the current release's size:

```
> du -sh /Applications/muCommander.app
192M	/Applications/muCommander.app

> du -sh build/macApp/muCommander.app
 42M	build/macApp/muCommander.app
```

**Comment by ahadas** [comment]
@sfuerte that's definitely the plan, to switch to newer version of Java
But I don't want to repeat the same mistake again - so let's make sure that issues that resulted from using Java 11 and resolved by switching back to Java 8 don't happen with the newer Java versions.
Relying on macOS users to install Java separately is problematic but producing a package that doesn't come with bundled JRE, as we have for Windows, is an option.
Why is it important for you to use Java 11 for the 'stable' releases? is there a reason other than reducing the size of the dmg file?

**Comment by sfuerte** [comment]
@ahadas, I'd say for me personally the main factor is to run an app natively, without an emulation on Apple Silicon (arm64) platform. 
Performance and security features introduced in Java 11 would be next. 

As for building with bundled JRE, `jlink` has been introduced since JDK 9, so I guess it should help with building it that way (and JDK 14's Packaging Tool definitely looks interesting - https://advancedweb.hu/a-categorized-list-of-all-java-and-jvm-features-since-jdk-8-to-15/#packaging)

PS: I did some poking around regarding Java 11 & arm64, need to complete a couple things and will push to a separate branch  so can discuss after. In short - the current `JavaAppLauncher` is limited to x86_64 only  at the moment: https://github.com/TheInfiniteKind/appbundler/issues/75 & https://github.com/crotwell/gradle-macappbundle/issues/73

**Comment by pinpins** [comment]
@sfuerte can you share the build to this github to test speed of mu on m1?

**Comment by ahadas** [comment]
done
