### ISSUE TITLE
Browsing Android devices via ADB interface

### ISSUE THREAD

**Issue by ahadas** [mucommander/mucommander#483]
Suggested in #18

**Comment by LeeBinder** [comment]
Hi Arik. I see you're nearing the 1.0 release - compliments. I'm wondering: have you added adb support?

**Comment by ahadas** [comment]
@LeeBinder yeah, we are enforced to do that as part of the transition to jpackage for creating the dmg, msi, rpm and deb files - jpackage requires the first digit to be non-zero.. About adb - no, it wasn't added and as far as I know, no one works on that at the moment so it's unlikely to be included in the upcoming version

**Comment by LeeBinder** [comment]
OK gotcha. Not a biggie - I'm fine using TrolCommander for adb at the moment.

On another note (don't want to open a separate issue for this because it might not be worth an issue): I integrated your 1.0.0 snapshot into (macOS) muCommander.app like I did before, like this:

![Bildschirmfoto 2022-02-20 um 09 45 49](https://user-images.githubusercontent.com/39203497/154835176-6cadfaf1-f555-467a-84b2-1e4a36020bf1.jpg), removed

```
bundle/
mucommander-os-linux-1.0.0.jar
mucommander-os-wind-1.0.0.jar
mucommander-os-openvms-1.0.0
```

and edited the info.plist to reflect 1.0.0-snapshot as I've done before. It's running fine, but it's not possible to access the preferences, neither via menu (no entry there) nor via ⌘ + ,

Do you have any idea if I'm missing a step, or if it's not possible anymore?

(let me know if you want me to open a new issue for this).

**Comment by LeeBinder** [comment]
@ahadas  I found your answer in a [Nov. 7 2020 comment of yours](https://github.com/mucommander/mucommander/issues/378#issuecomment-723426920) 👍 (and in the bundled ReadMe -> Java SE/ JDK 11).

One last question: will you again compile the final v.1.0.0 with Java 8 (which is still official Oracle LTS even as of now)?

**Comment by ahadas** [comment]
> One last question: will you again compile the final v.1.0.0 with Java 8 (which is still official Oracle LTS even as of now)?

No, the plan is to upgrade the bundled JRE to 17.0.2 - jpackage that simplifies the packaging was added in Java 14 and it seems that several issues that were reported are fixed in Java 17, so it seems like the right time to upgrade :)

**Comment by LeeBinder** [comment]
I see. That means: no more replacing bundled with a symlink to system Java unless users upgrade to the full JDK/ SE 17 since Oracle does not supply a separate JRE for 17 from what I know, correct?

Would you actually recommend installing Eclipse Adoptium v.17 OpenJDK rather than "official" Oracle 17 SE? Isn't Adoptium what you use, too, for dev?

**Comment by ahadas** [comment]
@LeeBinder the fact that I won't compile with Java 8 doesn't mean that it wouldn't work with Java 8. As a matter of fact, I haven't compiled with Java 8 for quite some time but[ I use the `--release 8` option](https://github.com/mucommander/mucommander/blob/release_0_9_7/build.gradle#L32) in order to generate artifacts that can run with Java 8. I've merged the changes that were needed to bundle the application with Java 17 and uploaded a [DMG of the nightly build](https://github.com/mucommander/mucommander/releases/download/nightly/muCommander-1.0.0.dmg) - I think it my work if you change the bundled JRE with that of Java 8 (note that it's located in a different place now - within the `Contents/runtime/Contents` folder of the muCommander.app. Would you like to give it a try to see if that replacement would work to see if there's still a point in releasing the script that changes the JRE?

And yes, I use Adoptium when developing on macOS and OpenJDK when I'm on Fedora (Java 17).

**Comment by LeeBinder** [comment]
Hi Arik. Thanks for the explanations. I adapted the script, but pretty much as expected after comparing the files and folders inside the two `Home` folders, latest system Oracle JRE 8 and `runtime/Contents/Home`: after creating all three symlinks (Home, info.plist, MacOS/libjli.dylib), muCommander wouldn't launch anymore. Even after first disabling Gatekeeper, then also re-codesigning the app, it still wouldn't launch.

So I'd say we can put the script  rtoest until Oracle officially recommends JRE 17.

**Comment by ahadas** [comment]
Version 1.3.0 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.3.0-1)
