### ISSUE TITLE
Google drive access is blocked

### ISSUE THREAD

**Issue by kangpaidjo** [mucommander/mucommander#504]
can't sign in google drive from mucommander

![20210903 10 09 43](https://user-images.githubusercontent.com/53972806/131944974-b8546ed0-45a2-46e1-b502-7e01f3bcbe90.jpg)

thanks

**Comment by ahadas** [comment]
Ack, thanks for reporting this. I've asked @m4xence  and @nrinaudo  to help with the registration of muCommander in Google in order to address that.

**Comment by panch0san** [comment]
I am trying to link by google account and seems that issue persists

**Comment by mic62** [comment]
same issue here for me.

**Comment by ahadas** [comment]
Yeah, we've reached the limit of 100 users for an unregistered application
We sorted out something that blocked the verification process (with Google) and asked to proceed with the verification process after releasing v1.0.0 two days ago. Hopefully the verification process will be completed soon and we'll be a registered application so that 100-users limit would drop

**Comment by ahadas** [comment]
The verification process was completed today.
I manage to access a Google account that I wasn't able to access before, can someone else also confirm this is solved?

**Comment by mic62** [comment]
Yes, I confirm that accessing my Google account does work now. But I can't save my credentials. The checkbox to do so is gray and not activated. So I always have to reconnect and confirm authorization again after switching back to my GDrive in muCommander.
Sidenote: Would be great if you could manage too an access to Google Photos in muCommander.

**Comment by ahadas** [comment]
> Yes, I confirm that accessing my Google account does work now.

Great, thanks! so I'm closing this issue then

> But I can't save my credentials. The checkbox to do so is gray and not activated. So I always have to reconnect and confirm authorization again after switching back to my GDrive in muCommander.

Yes, the "Store login and password" option is disabled on purpose - as we don't have it when connecting to Google drive or Dropbox. It shouldn't ask you to confirm authorization again though since we store the token - did you try to use the same "account" (i.e., the same gdrive://<account>)? how long it's been between the retries (if the token expired, the user must authenticate again)?

> Sidenote: Would be great if you could manage too an access to Google Photos in muCommander.

That's a nice idea! filed #619 for that

**Comment by mic62** [comment]
Hello Arik,

"It shouldn't ask you to confirm authorization again though since we store
the token - did you try to use the same "account" (i.e., the same
gdrive://)? how long it's been between the retries (if the token expired,
the user must authenticate again)?"

What I do is this:
1) Start muCommander
2) choose "GDRIVE" from dropdownlist
3) "Sign in with Google"
4) pick my account
5) allow muCommander access to my Googleaccount
6) Close browser window with message "Received verification code. You may
now close this window."
7) back in muCommander my name and Mailaddress is filled into the
connection window and I choose "connect"
8) now my GDrive contents is displayed in muCommander
9) now I switch to C:\\ via dropdownlist
10) and right after my c:\\ contents is displayed I switch back again to
"GDRIVE" via dropdownlist
11) now I am back to point 3) and have to authenticate again

So seems there is no token stored for me.

Greetings

Michael


Am Do., 21. Apr. 2022 um 23:06 Uhr schrieb Arik Hadas <
***@***.***>:

**Comment by ahadas** [comment]
@mic62 Ah ok, I see - that's because you invoked the connection dialog in step 10. You should rather connect with the same account that persisted token is correlated with. This is done by browsing `gdrive://<account-name>` where account-name is the one that is automatically filled in step 7 (or the you specify if you choose to override that). You can save that URL as a bookmark and that would allow you to select it using the dropdownlist that is mentioned in steps 2 and 9

**Comment by mic62** [comment]
Hello Arik,
thanks for the explanation, the way you described it works. I have created
a bookmark and can pick my GDrive from the dropdownlist.
Maybe it would be nice to have a checkmark "create bookmark" right inside
the connection dialog?
I created a post with a feature request (opening rar-files) in Github under
discussions...is this the correct location for such requests?
Greetings
Michael

Am Fr., 22. Apr. 2022 um 11:04 Uhr schrieb Arik Hadas <
***@***.***>:

**Comment by ahadas** [comment]
> Hello Arik, thanks for the explanation, the way you described it works. I have created a bookmark and can pick my GDrive from the dropdownlist.

Great :)

> Maybe it would be nice to have a checkmark "create bookmark" right inside the connection dialog?

That can be handy for users that may not be aware of the ability to set bookmarks but we'll need to think about what is the expected result when a bookmark with the same name already exist.. Feel free to file an issue and we can continue to discuss it there

> I created a post with a feature request (opening rar-files) in Github under discussions...is this the correct location for such requests?

Yeah, that's fine - we can later create an issue from the discussion, if needed. I commented there

**Comment by Tuulikk** [comment]
I guess I'm not going to do a bug report as this issue is reported here. 3 years later and the same thing.

"This app is blocked  This app tried to access sensitive info in your Google Account. To keep your account safe, Google blocked this access."

**Comment by ahadas** [comment]
> I guess I'm not going to do a bug report as this issue is reported here. 3 years later and the same thing.
> 
> "This app is blocked This app tried to access sensitive info in your Google Account. To keep your account safe, Google blocked this access."

please *do* file a new issue for a problem you face when there is no open issue and no closed issue targeted to the next version for it.
specifically about this one, yeah - we were asked by Google to update the privacy policy in order to resolve this problem again.

**Comment by ahadas** [comment]
filed https://github.com/mucommander/mucommander/issues/1289 to track the fix which would reduce the scope granted for the application as "drive" became restricted and now requires a costly verification process, otherwise the request is blocked
