### ISSUE TITLE
Provide a non bloated Fat Jar as a package

### ISSUE THREAD

**Issue by thevpc** [mucommander/mucommander#561]
Hi,
Thank you for your amazing app.  I'm trying to make mucommander available out of the box using nuts package manager (a new open source package manager we are working on https://github.com/thevpc/nuts). The Idea is to use a simple command like `nuts install mucommander` and voilà!
This is working right now, but my concern is that the jar you provide is bloated with all dependencies (50M is a very fat jar indeed).
Nuts Package Manager is able to solve dependencies at runtime and download them out of the box and that being said, fat jars and uber jars are no more an option. And this would be possible if the dependencies are not bundled and a simple descriptor for the dependencies is provided in the jar. 
So can you provide (as release, in maven central or github) separate jars?

**Comment by ahadas** [comment]
Hi @thevpc ,
muCommander is now based on OSGi so it is already comprised of a collection of jars, bundles in the terminology of OSGi, that are loaded by the Apache Felix framework.
You can inspect this layout by compiling and running the app from source using `./gradlew clean run` and checking the build/osgi folder. You'll find the following structure:
.
├── app
│   └── mucommander-core-0.9.8.jar
├── bundle
│   ├── activation-1.1.1.jar
│   ├── apache-bzip2-0.9.8.jar
│   ├── base64-2.3.8.jar
│   ├── bcprov-jdk15on-1.52.jar
│   ├── bined-core-0.2.0.jar
│   ├── bined-swing-0.2.0.jar
│   ├── commons-codec-1.3.jar
│   ├── commons-codec-1.9.jar
│   ├── commons-collections-3.2.2.jar
│   ├── commons-compress-1.20.jar
│   ├── commons-logging-1.1.1.jar
│   ├── commons-logging-1.2.jar
│   ├── commons-net-3.6.jar
│   ├── commons-vfs2-2.3.jar
│   ├── dd-plist-1.23.jar
│   ├── dropbox-core-sdk-3.1.5.jar
│   ├── google-api-client-1.23.0.jar
│   ├── google-api-services-drive-v3-rev110-1.23.0.jar
│   ├── google-http-client-1.23.0.jar
│   ├── google-http-client-jackson2-1.23.0.jar
│   ├── google-oauth-client-1.23.0.jar
│   ├── google-oauth-client-java6-1.23.0.jar
│   ├── google-oauth-client-jetty-1.23.0.jar
│   ├── guava-jdk5-17.0.jar
│   ├── hamcrest-core-1.1.jar
│   ├── httpclient-4.0.1.jar
│   ├── httpclient-4.5.jar
│   ├── httpcore-4.0.1.jar
│   ├── httpcore-4.4.1.jar
│   ├── jackson-annotations-2.10.0.jar
│   ├── jackson-core-2.10.0.jar
│   ├── jackson-core-2.1.3.jar
│   ├── jackson-core-2.7.4.jar
│   ├── jackson-core-asl-1.9.13.jar
│   ├── jackson-databind-2.10.0.jar
│   ├── jackson-mapper-asl-1.9.13.jar
│   ├── javax.jws-api-1.1.jar
│   ├── java-xmlbuilder-1.1.jar
│   ├── javax.xml.soap-10.0-b28.jar
│   ├── javax.xml.soap-api-1.3.5.jar
│   ├── jaxb-api-2.2.9.jar
│   ├── jaxrpc-api-1.1.jar
│   ├── jaxws-api-2.2.12.jar
│   ├── jcifs-1.3.17.jar
│   ├── jets3t-0.9.4.jar
│   ├── jetty-6.1.26.jar
│   ├── jetty-util-6.1.26.jar
│   ├── jline-2.14.2.jar
│   ├── jmdns-3.5.5.jar
│   ├── jms-1.1.jar
│   ├── jsch-0.1.55.jar
│   ├── json-simple-1.1.1.jar
│   ├── jsr305-1.3.9.jar
│   ├── junit-4.10.jar
│   ├── junrar-4.0.0.jar
│   ├── jzlib-1.1.3.jar
│   ├── libguestfs.jar
│   ├── logback-classic-1.2.3.jar
│   ├── logback-core-1.2.3.jar
│   ├── mail.osgi-1.4.jar
│   ├── mucommander-archiver-0.9.8.jar
│   ├── mucommander-command-0.9.8.jar
│   ├── mucommander-commons-collections-0.9.8.jar
│   ├── mucommander-commons-conf-0.9.8.jar
│   ├── mucommander-commons-file-0.9.8.jar
│   ├── mucommander-commons-io-0.9.8.jar
│   ├── mucommander-commons-runtime-0.9.8.jar
│   ├── mucommander-commons-util-0.9.8.jar
│   ├── mucommander-encoding-0.9.8.jar
│   ├── mucommander-format-ar-0.9.8.jar
│   ├── mucommander-format-bzip2-0.9.8.jar
│   ├── mucommander-format-gzip-0.9.8.jar
│   ├── mucommander-format-iso-0.9.8.jar
│   ├── mucommander-format-libguestfs-0.9.8.jar
│   ├── mucommander-format-lst-0.9.8.jar
│   ├── mucommander-format-rar-0.9.8.jar
│   ├── mucommander-format-sevenzip-0.9.8.jar
│   ├── mucommander-format-tar-0.9.8.jar
│   ├── mucommander-format-xz-0.9.8.jar
│   ├── mucommander-format-zip-0.9.8.jar
│   ├── mucommander-os-api-0.9.8.jar
│   ├── mucommander-os-linux-0.9.8.jar
│   ├── mucommander-os-macos-0.9.8.jar
│   ├── mucommander-os-openvms-0.9.8.jar
│   ├── mucommander-os-win-0.9.8.jar
│   ├── mucommander-preferences-0.9.8.jar
│   ├── mucommander-process-0.9.8.jar
│   ├── mucommander-protocol-api-0.9.8.jar
│   ├── mucommander-protocol-dropbox-0.9.8.jar
│   ├── mucommander-protocol-ftp-0.9.8.jar
│   ├── mucommander-protocol-gdrive-0.9.8.jar
│   ├── mucommander-protocol-http-0.9.8.jar
│   ├── mucommander-protocol-nfs-0.9.8.jar
│   ├── mucommander-protocol-ovirt-0.9.8.jar
│   ├── mucommander-protocol-registry-0.9.8.jar
│   ├── mucommander-protocol-s3-0.9.8.jar
│   ├── mucommander-protocol-sftp-0.9.8.jar
│   ├── mucommander-protocol-smb-0.9.8.jar
│   ├── mucommander-protocol-vsphere-0.9.8.jar
│   ├── mucommander-translator-0.9.8.jar
│   ├── mucommander-viewer-api-0.9.8.jar
│   ├── mucommander-viewer-binary-0.9.8.jar
│   ├── mucommander-viewer-image-0.9.8.jar
│   ├── mucommander-viewer-pdf-0.9.8.jar
│   ├── mucommander-viewer-text-0.9.8.jar
│   ├── org.apache.felix.scr-2.0.12.jar
│   ├── org.apache.felix.shell-1.4.3.jar
│   ├── osgiaas-cli-api-0.7.jar
│   ├── osgiaas-cli-core-0.7.jar
│   ├── osgiaas-common-0.7.jar
│   ├── paged_data-0.2.1-SNAPSHOT.jar
│   ├── sdk-4.4.5.jar
│   ├── servlet-api-2.4.jar
│   ├── servlet-api-2.5-20081211.jar
│   ├── slf4j-api-1.7.32.jar
│   ├── vim25.jar
│   ├── xz-1.9.jar
│   └── yanfs-1.4.jar
├── conf
│   ├── config.properties
│   └── logback.xml
├── mucommander-0.9.8.jar
├── run.bat
├── run.sh
└── system-libs
    └── mucommander-0.9.8.jar

I do plan to publish jars to maven central at some point but only/mostly those that serve for extensions so it would be easier to develop plugins for muCommander. There's no much point in publishing mucommander-core for instance since it's not a library/reusable component

Please let me know if that's what you were looking for

**Comment by thevpc** [comment]
Thank you @ahadas,
It would be great indeed to do so (publishing to maven) including **mucommander** and **mucommander-core**. My incentive for this is that the app is then available from within a single repo and this allows other devs to embed the whole app if they want to. 
And that being said, because you are using OSGI, does the dependencies **need to be** under the _bundle_ folder? can we provide location for each of them at some point somehow (commandline) not to duplicate shared dependencies between other installed apps?

**Comment by ahadas** [comment]
@thevpc yes, the dependencies have to be under the `bundle` folder for the infrastructure to load them with the default configuration. One can change [that setting](https://github.com/mucommander/mucommander/blob/0.9.7-1/build.gradle#L129) to point to another folder that contains the bundles. Having a path per dependency would be complicated because you'd also need to handle transactive dependencies..

About `mucommander` and `mucommander-core`, they are not part of the API for other apps so I don't plan to publish them. However, under the terms of GPLv3 - others can use the sources or publish those jars, if they find them useful
