### ISSUE TITLE
'Size' column too narrow when language is German

### ISSUE THREAD

**Issue by Andreas0602** [mucommander/mucommander#668]
The automatic determination of the column width does not work properly with some LAFs when the language is German. See screenshots.

- **VAqua not OK:**
<img width="382" alt="VAqua not OK" src="https://user-images.githubusercontent.com/79788982/172131526-053d04ea-1769-4677-86c5-65c2ed2db15b.png">

- **FlatLaf OK:**
<img width="383" alt="FlatLaf OK" src="https://user-images.githubusercontent.com/79788982/172131572-3ab97cb6-d487-4cbc-b009-d789528fcbe1.png">

- **FlatLaf not OK:**
<img width="379" alt="FlatLaf not OK" src="https://user-images.githubusercontent.com/79788982/172131596-89fe5af2-94ca-43ac-b9fa-cd1037e9c64c.png">

**Comment by ahadas** [comment]
@Andreas0602 while I see why seeing a truncated string could seem like an bug, it's done this way by design. think about it this way - imagine we'll calculate the width of each column in a way that ensures the whole title is presented, then the 'permissions' column would be much wider than it usually needs to be, right? I don't think it's that important to see the whole title - for the first time, one can see it using the tooltip and once realizing what each column is about, the titles are less important
