### ISSUE TITLE
Renaming is broken in version 1.0.1

### ISSUE THREAD

**Issue by sebastian-lempert** [mucommander/mucommander#680]
In the [release notes](https://raw.githubusercontent.com/mucommander/mucommander/1.0.1-1/package/readme.txt) you can read "Changed the rendering of the text field which is used when renaming a file/folder through the file table". Probably the corresponding changes also did change the way you are able to rename a file in a bad way?

If I try to rename a flle in version 1.0.1 on macOS the following happens:

1. After pressing Shift + F6 I am not able to move the cursor within the renaming text field anymore. If I try to move the cursor while editing mode is active the editing mode will immediately be ended.
2. After the editing mode is activated you can change the file name by simple typing in the new file name. In doing so unfortunately it's only possible to change the complete flle name since moving the cursor isn't possible anymore. Thus moving the cursor was very useful since most of the time you only want to change some part of the filename and not everything. Changing a part of the file name now means that you have to retype everything that should not be changed.
3. Furthermore I am just not able to change the file extension anymore since the selected text to be changed always only is the filename without the extension. Thus there is just no possibility to change the extension anymore.

**Comment by ahadas** [comment]
@sebastian-lempert thanks for reporting this, it sounds like a bug but I'll need more information on how to reproduce it
that's how it behaves on my machine:

https://user-images.githubusercontent.com/6020068/176515825-33fe42fe-4d3c-4ed5-a6fa-219eb9af1e00.mov

if it doesn't behave the same way on your machine, it would be best to share a recording of how it behaves or provide more details on what can be different on your machine compared to the recording above

**Comment by Andreas0602** [comment]
FWIW, I'm also using muCommander v1.0.1 on macOS, and I don't have the problem described by @sebastian-lempert.

However, I would like to mention that the way how muCommander highlights text during renaming does not follow the usual conventions. After pressing Shift + F6, the whole base name of file will be selected, and when type some text, the whole base name will be replaced by the text you've typed. That's perfectly okay, but what's not okay is that muCommander will display the whole selected base name with black text color on white background. It should be displayed with white text color on blue background. At least that's how other file managers behave, for example Finder or Total Commander.

Furthermore, after pressing Shift + F6, when you move the cursor (instead of typing text), you can modify parts of the file name without completely replacing the whole existing name. That's also perfectly okay, but what's not okay is that muCommander will display the file name with white text color on blue background. It should be displayed with black text color on white background.

I've attached a video how it is done in Finder (and how it should also be done in muCommander in my opinion).

https://user-images.githubusercontent.com/79788982/176861522-f54ee850-e7c6-4648-8829-742f0b2988ad.mov

I'm aware that the theme can be changed in the preferences, but unfortunately it's not possible to change it in a way that muCommander behaves like Finder and other file managers. At least I wasn't able to do so.

@ahadas, do you agree to my point of view? If so, I can open a new ticket for this issue.

**Comment by ahadas** [comment]
> FWIW, I'm also using muCommander v1.0.1 on macOS, and I don't have the problem described by @sebastian-lempert.

@Andreas0602  thanks for the confirmation, this means that this issue might be specific to a particular setting and thus hard to reproduce - @sebastian-lempert please reopen if there's more data that can be provided or ideally a way to reproduce that

> However, I would like to mention that the way how muCommander highlights text during renaming does not follow the usual conventions. After pressing Shift + F6, the whole base name of file will be selected, and when type some text, the whole base name will be replaced by the text you've typed. That's perfectly okay, but what's not okay is that muCommander will display the whole selected base name with black text color on white background. It should be displayed with white text color on blue background. At least that's how other file managers behave, for example Finder or Total Commander.

Yeah, I have few back and forth attempts that ended up in this state and I'll explain - I believe the theme in mucommander is more configurable than in, let's say, Finder. this makes it difficult to chose a specific background/foreground color for the renaming view because imagine that if that color is already used, you won't even notice that the text is selected. One way to solve this could have been to add another setting for that color but I thought it would over complicate the settings of a new theme (it would be hard to explain where that color comes into play). What I ended up with is this state - not that the colors that are used are those for the normal (non-selected) rows, and that way it is always noticeable.

> Furthermore, after pressing Shift + F6, when you move the cursor (instead of typing text), you can modify parts of the file name without completely replacing the whole existing name. That's also perfectly okay, but what's not okay is that muCommander will display the file name with white text color on blue background. It should be displayed with black text color on white background.

This part is technically complicated - we use a JTextField behind the scenes, it's just "invisible" now. It has four relevant properties: foreground, background, selectedColor, selectedTextColor. In the described scenario the text is not selected so the last two are irrelevant. If we change foreground and background to something else, the text field would be visible which doesn't look good. Had we had a way to set the JTextField with background colors, one for the text and another one for space we don't have text in, it would have made sense.

> I've attached a video how it is done in Finder (and how it should also be done in muCommander in my opinion).
> 
>  Bildschirmaufnahme.2022-07-01.um.10.44.53.mov 
> I'm aware that the theme can be changed in the preferences, but unfortunately it's not possible to change it in a way that muCommander behaves like Finder and other file managers. At least I wasn't able to do so.
> 
> @ahadas, do you agree to my point of view? If so, I can open a new ticket for this issue.

The first part is maybe non-standard but unless we have a way to pick a "good" color (i.e., that doesn't conflict with other colors) then I would keep it as is. I don't mind that it's different than Finder or Total Commander, we don't have to be aligned with other tools as long as it works for us. But if you have a suggestion, maybe based on what's in Total Commander, then please start a discussion and let's talk about it.

As for the second part, I understand what you mean but it's unlikely that I'll be able to get to that, I think there are more important things on my/our plate. But sure, you can file a bug and we'll see if anyone picks it up, if you think it's important
