### ISSUE TITLE
Authentication error with Samba 4.5.1 share

### ISSUE THREAD

**Issue by futur-tech** [mucommander/mucommander#75]
Context : Samba 4.5.1 ActiveDirectory on Debian Jessie server. Shares are on this server. Samba has been compiled from source.
Client : MacOS X 10.10 and 10.12.

When I try to connect to an SMB share on this server, the behaviour of mucommander depends of the version : 
version 0.9.0 : I get the authentication failure despite the credentials are correct.
version 0.9.1 : mucommander get the 'shares' list, but doesn't show the content of the share (=empty) if I clic on that share.
No error on samba logs. 

Exactly the same configuration on two older customer installation (Samba 4.4.2, 4.1.6) works fine with both version of mucommander.
MacOS Finder or 'Path Finder' connects fine in all cases.

It is quite a shame because mucommander is the only File Manager that quite fast responsive when connecting threw a slow VPN link...

**Comment by ahadas** [comment]
@futur-tech , and is there any error in the muCommander's log?

**Comment by futur-tech** [comment]
@ahadas ,Sorry for the delay.
Where should be this log file on OS X ? I didn't find it in /var/log or ~/Library/Logs/.

**Comment by ahadas** [comment]
@futur-tech , I reproduced this with my server and I have some good news and bad news..
Apparently, as from samba 4.5 the authentication method NTLMv1 that is used by the JCIFS library which we use in muCommander is disabled by default (due to security issues). It has been suggested to use Jespa, a library that is not open source, in order to authenticate using one of the recommended authentication methods.
However, you can enable NTLMv1 by adding ```ntlm auth = yes``` in /etc/samba/smb.conf that resides at your server (don't forget to restart the smbd service afterwards) and then muCommander will be able to authenticate.

**Comment by futur-tech** [comment]
@ahadas,
Yes it works with ntlm. auth = yes !!! Thank you. I'm not surprised of such behavior in the samba development.
One thing that may help user : warn the user in error message that mucommander requires settings to connect to samba >= 4.5 and refer to the documentation.
Again, thank you very much of this debug.

**Comment by verybigelephants** [comment]
has there maybe been some update to the JCIFS library so we can get an actual fix instead of enabling an unsecure way of authorisation on the server side? :(

or maybe a mucommander branch that would use Jespa that uses the good, secure way of authentication?
