### ISSUE TITLE
Project doesn't properly import to Idea

### ISSUE THREAD

**Issue by pskowronek** [mucommander/mucommander#753]
muC Project doesn't properly import to Idea - dependencies to JediTerm are not properly resolved in `TerminalWindow` in `mucommander-core` 

This started when JediTerm libs have been moved to separate sub-project `jetbrains-jediterm`

Tried to look at it, but so far I don't know why it doesn't work. Can someone explain how `comprise` work in muC gradle dependencies? Or any link to a documentation about it (I was unable to google anything about it :/).

A nasty workaround is to add external dependency to jetbrains-jediterm/build/libs/jetbrains-jediterm-1.1.0.jar.

**Comment by ahadas** [comment]
> Tried to look at it, but so far I don't know why it doesn't work. Can someone explain how `comprise` work in muC gradle dependencies? Or any link to a documentation about it (I was unable to google anything about it :/).

yeah, you won't find it in Google because it's specific to muCommander but the concept is not common:
we defined `comprise` as a configuration type that is like compileOnly for all projects:
```java
configurations {
    compileOnly.extendsFrom comprise
}
```
and then each project can set dependencies with this configuration and within the `jar` section to do something like:
```groovy
from configurations.comprise.collect { it.isDirectory() ? it : zipTree(it).matching {
    include ...
}
```
in order to include content from these dependencies in the target of the project

> A nasty workaround is to add external dependency to jetbrains-jediterm/build/libs/jetbrains-jediterm-1.1.0.jar.

I think it's ok to do this as long as the dependency is not a runtime dependency
did you try with compileOnly?

**Comment by ahadas** [comment]
> did you try with compileOnly?

I've set compileOnly dependencies that solved the issue for me but I'm using Eclipse, @pskowronek could you please check with IntelliJ IDEA?

**Comment by pskowronek** [comment]
> > did you try with compileOnly?
> 
> I've set compileOnly dependencies that solved the issue for me but I'm using Eclipse, @pskowronek could you please check with IntelliJ IDEA?

I was about to take care of it, but you were faster :) I've checked your changed and it works good.

**Comment by ahadas** [comment]
great, thanks!
