### ISSUE TITLE
Please open enclosing folder tab in same pane as search results

### ISSUE THREAD

**Issue by Andreas0602** [mucommander/mucommander#762]
When you do a file search in the right panel of muCommander, the search results will be also shown in the right panel. That's fine. Now, when you right-click a file in the search results and select "Shown in enclosing folder", muCommander will open a new tab showing the enclosing folder. That's also fine. However, it is inconvenient that this tab is on the left panel. It should be on the right panel (or in general: on the same panel on which the search was done). That would be more convenient in practice.

**Comment by ahadas** [comment]
the reason for doing this was to keep the search results visible, @Andreas0602 why is it more convenient to open the new tab in the same panel as that of the search results?

**Comment by Andreas0602** [comment]
If you implemented my proposal, you would still have all search results available in their own tab.

It would be more convenient in the following use case, for example: After executing 'show enclosing folder', you want to use the F5 key to copy a file from that enclosing folder into the folder which was visible in the other pane before you executed 'show enclosing folder'. It's not possible, because both folders are in different tabs in the same pane. You could do it via command+C, switch tab, command+V, but it's inconvenient.

**Comment by ahadas** [comment]
> If you implemented my proposal, you would still have all search results available in their own tab.

right, but try the following:
1. open two tabs in the panel
2. in one of those tabs, initiate a search
3. when the search is completed, switch to the other tab
4. switch back to the tab of the search
At this point, you won't see the search results because they are not cached.
There was an issue with caching, I don't remember its details now but it lead to this design. if the results are not cached, and thus when switching back to the search tab in your proposal you would need to re-trigger the search, I don't see much point in opening a new tab at the same panel and switching to that tab

> It would be more convenient in the following use case, for example: After executing 'show enclosing folder', you want to use the F5 key to copy a file from that enclosing folder into the folder which was visible in the other pane before you executed 'show enclosing folder'. It's not possible, because both folders are in different tabs in the same pane. You could do it via command+C, switch tab, command+V, but it's inconvenient.

I see but that's a bit unique case, doesn't it? I'd expect the user to search for the files that should be copied rather than searching for another file in their folder..

**Comment by Andreas0602** [comment]
Hmm, meanwhile I'm not sure whether it was a good design decision to show the search results directly in the file pane. It seems to create a number of problems. Most other file managers, including major ones like Total Commander or Commander One, show the search results in an extra window.

**Comment by ahadas** [comment]
> Hmm, meanwhile I'm not sure whether it was a good design decision to show the search results directly in the file pane. It seems to create a number of problems. 

yes, showing the search as a browsable file introduced few challenges but it also has quite a few benefits like the ability to operate on the search results as any other files in a foler/archive (for instance, marking some of them and copy them to the location on the other panel with F5).

> Most other file managers, including major ones like Total Commander or Commander One, show the search results in an extra window.

once again, we don't try to duplicate other file managers here so the fact it's done this way elsewhere is not a good argument..

going back to the original issue, would you find it more useful to open the enclosing folder within the tab that presented the search results rather than in a new tab? it would be closer to having the search results in a separate window and selecting 'open enclosing folder' from that window..

**Comment by Andreas0602** [comment]
> going back to the original issue, would you find it more useful to open the enclosing folder within the tab that presented the search results rather than in a new tab? it would be closer to having the search results in a separate window and selecting 'open enclosing folder' from that window..

Indeed, that would be better in my opinion. And yes, it would be similar to what other file managers are doing. I don't mean to upset you with that statement. I just want to say that you can't go much wrong if you implement it that way. Also, it's good to meet the user's expectations. Users tend to prefer what they already know.

**Comment by ahadas** [comment]
> > going back to the original issue, would you find it more useful to open the enclosing folder within the tab that presented the search results rather than in a new tab? it would be closer to having the search results in a separate window and selecting 'open enclosing folder' from that window..
> 
> Indeed, that would be better in my opinion.

ok then, this should be an easy change

> And yes, it would be similar to what other file managers are doing. I don't mean to upset you with that statement. I just want to say that you can't go much wrong if you implement it that way. 

nah, it doesn't upset me - I just find this argument irrelevant and I see it too often in the last couple of days :)

> Also, it's good to meet the user's expectations. Users tend to prefer what they already know.

yes, but the thing is that I don't try to imitate other file managers here. if one likes a particular file manager, let's say total commander or commander one - that user shouldn't expect us to implement everything that exists there or implement certain things exactly the way they are implemented there just to have a similar application that is open source and therefore free. we can talk about concrete things and see if they are aligned with the vision of muCommander, if they are I'd be happy to accept them. if they are not accepted (and our thread about menus that follow the corresponding native menus), then one should either convince why they are aligned with the vision of muCommander or look for alternatives (either within muCommander or complementary tools or alternative tools)
