### ISSUE TITLE
JRELoadError

### ISSUE THREAD

**Issue by Matasumo** [mucommander/mucommander#79]
Hi,
i made an update from MuCommander 0.9.0 to 0.9.1 on OS-X 10.6.8
After installation and try to launch i get an "JRELoadError"
( Little rare information, isn't it ?   ;-)
Java SE 6 in version 1.6.0_45-b06-451 is installed on S.L.

And now.... ???

**Comment by ahadas** [comment]
@Matasumo , which dmg file did you download? can you please try [this one](https://github.com/mucommander/mucommander/releases/download/0.9.1/mucommander-0.9.1-apple-java.dmg)

**Comment by Matasumo** [comment]
Hi Arik,
your link works now !   :)

In the "about" window from the old version 0.9.0 is a link to this website :
https://github.com/mucommander/mucommander/releases/tag/0.9.1

there i choosed the third one "mucommander-0.9.1.dmg"
which is smaller.

Maybe a little description listening the differences might be helpful.

Thanks a lot for your help !!
Dieter

2017-03-03 18:11 GMT+01:00 Arik Hadas <notifications@github.com>:

**Comment by Matasumo** [comment]
Hi Arik,
sorry, have an other problem with login to another mac in our local network.
In normal Finder window the other machine appears, i simply click and have
access to enabled folders and files - all's no problem.

Within muCommander i can't build a connection. It should work over
"device", isn't it ?
I tried volumes, device and a connection over Network share and other stuff
- the other machine did'nt appear...... !
How to manage that ??

Dieter

2017-03-03 18:11 GMT+01:00 Arik Hadas <notifications@github.com>:

**Comment by ahadas** [comment]
@Matasumo , muCommander doesn't automatically resolve computers that have file sharing turned on, as Mac operating system does. You'll need to follow few steps in order to connect to such machines:
1. Browse ```Apple menu > System Preferences -> Sharing``` on the machine you'd like to connect to.
2. You'll see that ```File Sharing``` is turned on, select it and you'll find a url that starts with 'smb://' that you can connect to.
3. In muCommander enter this url and provide the required authentication information. This should allow you to browse the shared files on the remote machine.

I'm closing this issue since the original problem is resolved. Feel free to file another issue if the process described above doesn't work for you.
