### ISSUE TITLE
Undesired gutter in new editor when line numbers are turned off

### ISSUE THREAD

**Issue by Andreas0602** [mucommander/mucommander#874]
When line numbers are turned off, there's an undesired gutter in the new editor.

This issue did not occur in earlier versions of the new editor. For example, see the screenshot in #806.
<img width="612" alt="screenshot" src="https://user-images.githubusercontent.com/79788982/221399436-196bb41d-b63b-4c8a-9dae-23294aeb8a4e.png">

**Comment by pskowronek** [comment]
That gutter is used to show 'code folding' markers (if option is enabled):
![obraz](https://user-images.githubusercontent.com/360665/221404338-3ca11df8-67cb-4133-99be-a70fe959ce73.png)

**Comment by pskowronek** [comment]
It can be worked around in muC, however it would be better to raise a bug in RSyntaxTextArea, I will try to do it later today.

**Comment by pskowronek** [comment]
Since I saw something similar (when line number panel was toggled) I did then a fix/workaround, which cause this bug. I've removed the then fix and moved the line to show folding gutter to `TextEditorImpl.setFoldIndicatorEnabled`.

I'll think as to whether to raise a bug to RSyntaxTextArea as toggles for line number and code folding work differently (the latter one requires also to show the gutter additionally in some cases).
