### ISSUE TITLE
Reporting a bug / finding help

### ISSUE THREAD

**Issue by DannyBen** [mucommander/mucommander#9]
All the paths to report a bug and find help or documentation are broken.

I have tried all the links in the top bar on the [muCommander home page](http://www.mucommander.com/) including the [Wiki](http://trac.mucommander.com/) and [Forum](http://www.mucommander.com/forums_maintenance.php)

I have tried the [Wiki on Atlassian](https://mucommander.atlassian.net/wiki/) which is linked at the bottom of the [Readme](https://github.com/mucommander/mucommander)

I have tried sending a bug report through the "Report a Bug" menu item (which worked a few days ago I think, and now is also broken).

**Comment by ahadas** [comment]
Unfortunately, several parts in the home page are currently broken (we will solve that soon).
The way to go is to use jira. Are you saying that you didn't manage to fill a bug in jira? what was the problem you encountered?

**Comment by DannyBen** [comment]
Thanks for the quick response.

The thing is I love muCommander, and trying to make it fit my needs.

Where is the Jira page?
Clicking "Report a bug" from muCommander (nightly build) leads to [this broken page](http://www.mucommander.com/bugs/) which redirects to the broken trac subdomain.

I encountered several issues, not sure if bugs or misuse on my part, like:

* I was unable to make anything in commands.xml work. For example I tried making F4 open Sublime Text as editor with many variations on this line `<command alias="edit" value="C:\Program\ Files\Sublime\ Text\ 2\sublime_text.exe $f" type="system"/>`
* On my Windows machine, right clicking a file has "Open With" which is always grayed out. Wanted to know how to add commands to this submenu
* SFTP does not work for me. Using a passphrase protected private key. I am easily able to login using another client (WinSCP) but with muCommander I get invalid credentials.
* Wanted to read a little more about commands.xml in order to add more commands to it (since muCommander suppresses the native Windows right click menu) - for example, wanted to add `Ctrl+Shift+V = send to VirusTotal`, and `Ctrl+D = Dos Prompt Here`
* Wanted to suggest to add a "Cut" operation on a file in addition to copy and move
* Wanted to suggest a preferences setting to suppress the Move dialog (always move to the other panel).
* Wanted to suggest a "Duplicate File" operation, or even better, simply allow `Ctrl+C then Ctrl+V` and paste the file as `Original Name - Copy` or `Original Name (1)` or similar. Right now, copy-then-paste results in an error dialog.

Footnote:  
For now, I have solved the hotkeys / commands.xml problems I have above by simply writing a AutoHotkey script that overrides the commands I want - so F4 sends Alt+Shift+C to muCommander to copy the selected file path, and then I handle it in AutoHotkey.

And some more...

**Comment by ahadas** [comment]
The jira page: https://mucommander.atlassian.net/

No problem, feel free to open bugs/enhancements for these things and we'll discuss them in jira.

**Comment by DannyBen** [comment]
Ok, thanks.
Should I also open questions there? Like I know I am probably doing something wrong with commands.xml - so not really a bug or feature request but rather something I would probably post in a forum or something...

**Comment by aadrian** [comment]
Why not simply use GitHub for the issues too? It's much simpler, and the users don't need to create "yet another account"?

**Comment by DannyBen** [comment]
@aadrian I second that. Jira is much less convenient, especially for people who don't use it on a regular basis.

**Comment by ahadas** [comment]
Indeed, one of the advantages of using github for issues is that it is managed in the same place where the code repository is so developers can reuse their github account.

I think there are couple of arguments for using a separate ticketing system:
1. ticketing systems provide many capabilities that are missing in github such as: voting, attachments, relations between bugs (that cannot be represented with labels) and so on
2. users who are not developers don't have account on github, and I think that it's better for them to open an account on jira and then get a system that is more intuitive for them to use instead of asking them to register on github

**Comment by aadrian** [comment]
> 1. ticketing systems provide many capabilities that are missing in github

Do we really need them? I suppose not :). 
Yes, companies need them, to ensure proper metrics, KPIs, workflow policies, etc.

> 2. users who are not developers don't have account on github, and I think that it's better for them to open an account on jira

Why shouldn't these users just open account in Github? For simple use cases, or non-technical users, JIRA is much more confusing than the GitHub issues.

**Comment by DannyBen** [comment]
I also think Jira is much more confusing than Github. If a non developer user who does not know any of them needs to get used to something, Github would be easier for them I suppose.

**Comment by ahadas** [comment]
@aadrian , I think that the option for voting is important not only for companies but also for open source projects, where you want to start with things that are both achievable and requested by many users. Also attachments can be really useful for bugs that are related to the ui (screenshots) and log files - not only for companies.

@aadrian , @DannyBen , right - for users it could be more complicated to filter all bugs for a particular release using jira for example. The thing is that users should be provided with an easy way to fill new bug and being able to trace its progress. Jira provides a very nice and customizable form for new bugs/enhancements. If you think the current form is not good enough, you're welcome to suggest things to improve there. Once the user filled a bug and have an account, he can see all his bugs and their progress with a relative ease.
It might be that the current look of our jira is not perfect. I didn't finish the work on it. I agree that github's ui is simpler but it lacks features that want to have and it is a more technical service, not intended for non-technical users. I do think we need to have a system that is more tailored for non-technical users along with github. I thought about the authentication aspect before, but I didn't find any way to use github's login or something like openid. Anyway, I don't think that for the sake of using the same account for code repository and issue tracking, we need to use a tool that is less suitable for mucommander's non-technical users.

**Comment by DannyBen** [comment]
@aadrian - of course, what works for the owner(s) of the project is probably the best option. If you guys are comfortable and getting value from Jira, than that is the right choice for you, no argument here.

I can tell you that even as a developer, I feel "out of context" in Jira, especially when joining in on someone else's project. It is bloated, but thats my opinion.

If you are looking for a less technically-heavy board (with votes!) - have you considered Trello?

I for one, had several issues / questions to report but after one or two postings in Jira, I just gave up. The process of looking if my issue was reported, and posting it was too cumbersome.

**Comment by aadrian** [comment]
@ahadas 
> Also attachments can be really useful for bugs that are related to the ui (screenshots) and log files - not only for companies.

Screenshots already work on Github - just drag and drop.

I'm using JIRA in many projects, and I know it's very flexible, and allows allot of stuff. 

However we've used in the last year successfully something very similar to GitHub in our intranet: https://github.com/takezoe/gitbucket and even if it's limited, the users much prefer this instead of JIRA (with customizations) or RedMine or other solutions we've tried.

Another issue is speed: JIRA is quite slow even when hosted by Atlassian itself :) - this aspect did not changed in the last 5 years :).

**Comment by hansgru** [comment]
Few points in favor of GitHub issues and infrastructure:

 - Google Code projects are to be migrated to GitHub
 - GitHub UI is mostly at least an order of magnitude faster than any JIRA installation I've seen. The same is true for the WIKI (so Confluence)
 - you can host even the website on GitHub - just point the domain. This can't be done easily with Atlassian right now. Extremely helpful for open source projects since they don't need hosting somewhere else.
 - You can connect pull requests or commits with issues - this is very useful for any project management.
 - Because most projects already ARE on GitHub, or are in the migration process to GitHub, most even non-technical people (potential users of mucommander) already have a GitHub account or will soon have one. This is definitely not true for a particular instance if JIRA.

So why not just keep things simple and have everything in one place?

**Comment by jcrben** [comment]
It seems odd to me that there's resistance to using something simple like Github when the official website isn't even working. It seems like the team is biting off a bit more than they can chew and it would be best to simplify and streamline. I'd say using Github is a good start to that.

**Comment by aadrian** [comment]
> I'd say it would be really helpful for these projects to merge.

+1 for merging and moving the issues and the wiki on GitHub too for simplicity.

**Comment by ahadas** [comment]
Thanks for the input guys.

**Comment by sebastian-lempert** [comment]
Maybe it is interesting to note that the above mentioned Jira page https://mucommander.atlassian.net/ seems to be broken for quite a while. Thus from my point of view the only remaining way to post bug reports / to find help is to use this GitHub issues section.

**Comment by rdiez** [comment]
I am also a newcomer. Before attempting to contribute to the project, I wanted to ask some questions. But some links on the website are still broken, others "under construction". There is no mailing list. I haven't used IRC much, but when I log on, there is nobody there. This is rather off-putting.

**Comment by ahadas** [comment]
Hi @rdiez ,
Regarding the website - yes, some parts are still missing, unfortunately. I hope to find some time for completing those parts as well soon, after releasing a new version that contains the fixes/changes on the master branch.
Mailing list - also right. We used to have a google group (https://groups.google.com/forum/#!forum/mucommander-dev) that is inactive for quite some time. I'm trying to avoid having too many channels that need to be monitored (besides twitter, GitHub issues/requests, IRC), but maybe we do need to revive the google group or to create a new mailing-list.
IRC - most of the time that I'm next to a computer I'm supposed to be logged in to the IRC channel. The last few days are not representative since I was on vacation with limited connectivity. That is the best channel to discuss stuff in my opinion. I'm usually there between 9:30 to 18:30 (UTC+3), we can chat there. Would it work for you?

**Comment by sdruskat** [comment]
How about a [Slack](https://slack.com/) channel instead of a Google group (and/or as a replacement for IRC)? Works well for software projects in my experience, can be used multidimensionally (via channels), and is free.

**Comment by rdiez** [comment]
I am more of an e-mail guy, so that I can easily find and reuse information later on.
Could you drop me a line at rdiezmail-temp2@yahoo.de , so that I get your e-mail address?

**Comment by aadrian** [comment]
> How about a Slack ..

Please no.

> Works well for software projects in my experience,

It doesn't:
 - it's not public
 - it can't be searched
 - it's a time sinkhole 
 - each project needs registration

For GitHub projects, if chat is required https://gitter.im is much better since it integrates easily and the same GitHub username can be used.

**Comment by sdruskat** [comment]
@aadrian True. Forgot about gittr.

**Comment by ahadas** [comment]
Thanks guys, gittr seems like a good option indeed.
I opened a room, let's give it a shot: [gittr](https://gitter.im/mucommander/Lobby?utm_source=share-link&utm_medium=link&utm_campaign=share-link)
