### ISSUE TITLE
Creating a file - inconsistent shortcut name & could we have Shift+F4?

### ISSUE THREAD

**Issue by dandv** [mucommander/mucommander#927]
I was trying to create a file with Shift+F4 (got use to it from Dos Navigator, NDN, Double Commander), and when that didn't work, I looked in the Shortcuts help:

![image](https://github.com/mucommander/mucommander/assets/33569/84428b35-bde7-46f3-bf59-3309d6d6044e)

The name was "Create file..." so I searched for it in Settings -> Shortcuts but found nothing...

<img width="595" alt="image" src="https://github.com/mucommander/mucommander/assets/33569/2cdc6639-c3c1-4b31-8ff4-ac8427316bb6">

...because it's called "Make file" there.

Having Shift+F4 by default / as an alternative would solve both problems :)

**Comment by ahadas** [comment]
thanks for filing this @dandv !

as for setting the default or alternative shortcut of the `Make file` action to Shift+F4, I think we better keep the default shortcut as Shift+F7 since the default shortcut of `Make directory` is set to F7, but I don't see an issue with setting the alternative shortcut to Shift+F4 (it's unused at the moment)

the first part of this issue was already addressed in [v1.3.0](https://github.com/mucommander/mucommander/releases/tag/1.3.0-1) - [actions in the preferences->shortcuts dialog can be filtered by their description](https://github.com/mucommander/mucommander/pull/931), that appears in the keyboard shortcuts dialog, as well.

**Comment by ahadas** [comment]
Version 1.4.0 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.4.0-1)
